#Nginx Servce
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8443
      protocol: TCP
      name: https
      cohesityPortTag: https-ui
      cohesityTag: ui
      cohesityEnv: INSIGHT_HTTPS_UI_PORT
---
#Nginx Pod Spec
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: athena-nginx_server:latest
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
---
# UI NodePort service.
apiVersion: v1
kind: Service
metadata:
  name: log-cleaner
  labels:
    app: log-cleaner
spec:
  type: ClusterIP
  selector:
    app: log-cleaner
  ports:
    - port: 4200
      protocol: TCP
      name: https
---
# UI Pod Spec.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: log-cleaner
  labels:
    app: log-cleaner
spec:
  replicas:
    fixed: 1
  selector:
    matchLabels:
      app: log-cleaner
  template:
    metadata:
      labels:
        app: log-cleaner
    spec:
      containers:
        - name: log-cleaner
          image: athena-log-cleaner
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
